[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd backend && npm install --omit=dev"]

[phases.build]
cmds = ["cd backend && npm run migrate"]

[start]
cmd = "cd backend && npm start"
