[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["echo 'No build step required for Node.js'"]

[start]
cmd = "cd backend && npm start"
