[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "cd backend && npm ci --omit=dev --prefer-offline",
  "npm cache clean --force"
]

[phases.build]
cmds = [
  "cd backend && node scripts/railway-setup.js"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"
PORT = "3001"
